version: "3.7"

services:
  web:
    container_name: dev_backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  redis:
    container_name: dev_redis
    image: redis
    ports:
      - 6379:6379
  celery:
    container_name: dev_celery
    build: .
    command: celery -A support worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: