# Generated by Django 3.2 on 2022-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[
                ('RS', 'Resolved'),
                ('UN', 'Unresolved'),
                ('DF', 'Deferred'),
            ],
                default='UN',
                max_length=2),
        ),
    ]
